# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Milestone Action

on:
  [push]
  # schedule:
  #   # * is a special character in YAML so you have to quote this string
  #   # First day of the month
  #   - cron: "*/5 * * * *"

jobs:
  create-milestone:
    runs-on: ubuntu-latest
    name: Create a Milestone
    steps:
      - name: Create a Milestone
        uses: foretheta/milestone-actions@development

        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
